name: Sync Fork

on:
  schedule:
    - cron: '0 */12 * * *' # every 12 hour
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.9
        with:
          owner: blackmatrix7
          base: master
          head: master
