name: Sync Fork

on:
  schedule:
    - cron: '0 */8 * * *' # every 8 hour
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.9
        with:
          owner: yqt
          repo: ios_rule_script
          base: master
          head: master
          merge_method: rebase
